DROP VIEW IF EXISTS warehouse.vw_reservation_stay_date_f CASCADE;

CREATE VIEW warehouse.vw_reservation_stay_date_f AS

SELECT
    s.record_id,
    s.source_id,
    lookup.f_lookup_source_by_id(s.source_id) sourceKey,
    s.internal_reservation_id,
    s.internal_property_id,
    lookup.f_lookup_property_by_id(s.internal_property_id) propertyCode,
    s.business_date,
    s.stay_date,
    s.arrival_date,
    s.check_in_datetime,
    s.departure_date,
    s.check_out_datetime,
    s.rate_code,
    s.rate_code_description,
    s.room_rate,
    s.currency_code,
    s.room_class,
    s.room_class_description,
    s.room_type,
    s.room_type_description,
    s.area_id,
    s.room_number,
    s.discount_amount,
    s.discount_percentage,
    s.discount_reason,
    s.room_revenue,
    s.food_revenue,
    s.other_revenue,
    s.total_revenue,
    s.non_revenue,
    s.tax,
    b.confirmation_number,
    b.reservation_key,
    b.booking_id,
    b.guarantee_code,
    b.reservation_status,
    b.cancellation_date,
    b.stay_rooms,
    b.stay_adults,
    b.stay_children,
    b.market_code,
    b.source_code,
    b.booked_room_class,
    b.booked_room_class_description,
    b.booked_room_type,
    b.booked_room_type_description,
    b.walkin_yn,
    b.complimentary_yn,
    b.house_use_yn,
    b.day_use_yn,
    b.vip_status,
    b.source_insert_date,
    b.source_update_date,
    b.booking_type,
    b.block_status,
    b.cancellation_code,
    b.channel,
    b.channel_type
FROM
	warehouse.reservation_stay_date_f s
	JOIN warehouse.reservation_business_date_f b ON b.business_date = s.business_date AND b.internal_reservation_id = s.internal_reservation_id
	JOIN warehouse.reservation_business_date_extension_f e ON e.business_date = s.business_date AND e.internal_reservation_id = s.internal_reservation_id;
