DELETE FROM lookup.lookup_ingestion_status;
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (-6, 'INGESTION_FAILED','Ingestion Failed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (-5, 'RDZ_WRITE_FAILED','Write to RDZ failed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (-4, 'WAREHOUSE_WRITE_FAILED','Write to warehouse tables failed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (-3, 'STAGE_WRITE_FAILED','Write to stage tables failed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (-2, 'S3_STREAM_READ_FAILED','Stream read from S3 failed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (1, 'SOURCE_RECEIVED','S3 Trigger received.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (2, 'S3_STREAM_READ_COMPLETE','Stream read from S3 completed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (3, 'STAGE_WRITE_COMPLETE','Write to stage tables completed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (4, 'WAREHOUSE_WRITE_COMPLETE','Write to warehouse tables completed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (5, 'RDZ_WRITE_COMPLETE','Write to RDZ completed.');
INSERT INTO lookup.lookup_ingestion_status(internal_status_id, code, status_description) VALUES (6, 'INGESTION_COMPLETE','Ingestion Completed.');