DROP VIEW IF EXISTS warehouse.vw_reservation_business_date_extension_f CASCADE;

CREATE VIEW warehouse.vw_reservation_business_date_extension_f AS

SELECT
	b.source_id,
    lookup.f_lookup_source_by_id(b.source_id) sourceKey,
	b.internal_reservation_id,
	b.internal_property_id,
    lookup.f_lookup_property_by_id(b.internal_property_id) propertyCode,
	b.business_date,
	b.stay_date,
	b.arrival_date,
	b.check_in_datetime,
	b.departure_date,
	b.check_out_datetime,
	b.rate_code,
	b.rate_code_description,
	b.room_rate,
	b.currency_code,
	b.room_class,
	b.room_class_description,
	b.room_type,
	b.room_type_description,
	b.area_id,
	b.room_number,
	b.discount_amount,
	b.discount_percentage,
	b.discount_reason,
	b.room_revenue,
	b.food_revenue,
	b.other_revenue,
	b.total_revenue,
	b.non_revenue,
	b.tax,
	b.confirmation_number,
	b.reservation_key,
	b.booking_id,
	b.guarantee_code,
	b.reservation_status,
	b.cancellation_date,
	b.stay_rooms,
	b.stay_adults,
	b.stay_children,
	b.market_code,
	b.source_code,
	b.booked_room_class,
	b.booked_room_class_description,
	b.booked_room_type,
	b.booked_room_type_description,
	b.walkin_yn,
	b.complimentary_yn,
	b.house_use_yn,
	b.day_use_yn,
	b.vip_status,
	b.source_insert_date,
	b.source_update_date,
	b.booking_type,
	b.block_status,
	b.cancellation_code,
	b.channel,
	b.channel_type,
    e.reservation_extension_data JSONB,
    e.etl_file_name,
    e.etl_ingest_datetime
FROM
	warehouse.reservation_business_date_extension_f e
	JOIN warehouse.vw_reservation_business_date_f b ON b.business_date = e.business_date AND b.internal_reservation_id = e.internal_reservation_id;
