-- FUNCTION: lookup.f_process_warehouse_onq_salt(character varying)

DROP FUNCTION IF EXISTS lookup.f_process_warehouse_onq_salt(bigint);
CREATE SCHEMA IF NOT EXISTS lookup;

CREATE OR REPLACE FUNCTION lookup.f_process_warehouse_onq_salt(etlBatchId bigint)
    RETURNS integer
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
DECLARE sourceId integer;
DECLARE partitionRecord record;
BEGIN
    SELECT
        internal_source_id INTO sourceId
    FROM
        lookup.lookup_source
    WHERE
        source_key = 'ONQ_SALT';
	DROP TABLE IF EXISTS t_stage_to_warehouse_onq_salt;
	CREATE TEMPORARY TABLE t_stage_to_warehouse_onq_salt AS
	SELECT
		o.*
	FROM
		stage.stage_batch b
		JOIN stage.stage_onq_salt o ON o.etl_batch_id = b.batch_id
	WHERE
		b.source_id = sourceId
		AND b.stage_completed_ind = true
		AND b.warehouse_completed_ind = false
		AND b.warehouse_transfer_start_timestamp IS NULL
		AND (b.batch_id = etlBatchId OR etlBatchId IS NULL);
    -- mark these records as picked up so that another run does not pick it.
	UPDATE
		stage.stage_batch b
	SET
		warehouse_transfer_start_timestamp = current_timestamp
	FROM
		t_stage_to_warehouse_onq_salt o
	WHERE
		o.etl_batch_id = b.batch_id;
    FOR partitionRecord IN SELECT DISTINCT partition_date FROM t_stage_to_warehouse_onq_salt WHERE partition_date IS NOT NULL
        loop
            PERFORM warehouse.f_create_table_partition('warehouse.onq_salt_f',CAST(partitionRecord.partition_date AS character varying));
        end loop;

    INSERT INTO warehouse.onq_salt_f
    (
        age,
        alert_overdue,
        appreciated_elite_tier_honors_rating,
        appreciated_honors_club_member_rating,
        appreciated_honors_member_rating,
        availability_accessibility_food_amenities_rating,
        aware_of_guarantee,
        bathroom_cleanliness_rating,
        brand,
        brand_conversion,
        brand_promise_rating,
        brand_promise_rating_QQ,
        brand_promise_rating_UP,
        breakfast_in_bag_rating,
        breakfast_item_quality_rating,
        canopy_breakfast_rating,
        checkin_date,
        checkin_type,
        checkout_date,
        complimentary_breakfast,
        condition_of_pool_rating,
        confirmation_number,
        conrad_concierge_rating,
        digital_checkin_map_usefulness_rating,
        digital_checkin_room_selection_rating,
        digital_checkin_satisfaction_rating,
        digital_key_front_desk_did_not_visit,
        digital_key_front_desk_info,
        digital_key_front_desk_obtain_info,
        digital_key_front_desk_other_reason,
        digital_key_front_desk_rating,
        digital_key_front_desk_report_problem,
        digital_key_front_desk_request_amenities,
        digital_key_rating,
        digital_key_room_selection_rating,
        digital_key_staff_handling_problem,
        efficiency_of_arrival_rating,
        environmental_programs_rating,
        evening_manager_reception,
        evening_tastings_rating,
        facility_id,
        front_desk_digital_rating,
        gender,
        grab_go_market_rating,
        guarantee_resolved_experience_rating,
        guest_room_cleanliness_rating,
        helpfulness_bell_staff_rating,
        helpfulness_breakfast_staff_rating,
        helpfulness_executive_lounge_staff,
        helpfulness_hotel_staff_rating,
        helpfulness_staff_evening_experience_rating,
        hgv_primary_purpose,
        honors_benefit_delivery_rating,
        honors_benefit_delivery_silver_rating,
        honors_member_welcome_rating,
        honors_tier,
        hotel_ground_apprearance_rating,
        housekeeping_acknowledge_rating,
        inncode,
        insert_datetime_utc,
        lobby_apprearance_rating,
        lobby_games_rating,
        lobby_reading_material_rating,
        luxurious_stay_rating,
        make_it_right_rating,
        mobile_opt_in,
        offered_cookie_ind,
        overall_accommodation_rating,
        overall_arrival_rating,
        overall_bar_experience_rating,
        overall_breakfast_experience_rating,
        overall_concierge_experience_rating,
        overall_departure_rating,
        overall_event_experience_rating,
        overall_exec_lounge_experience_rating,
        overall_experience_rating,
        overall_fitness_facility_rating,
        overall_food_beverage_experience_rating,
        overall_inroom_service_experience,
        overall_reception_experience_rating,
        overall_service_rating,
        overall_spa_experience_rating,
        owner_account_id,
        owner_account_name,
        owner_extract_type,
        partial_survey_flag,
        business_date,
        pay_access_premium_suite_rating,
        premium_suite_during_stay_rating,
        premium_suite_value_rating,
        primary_purpose,
        problem_billing_rates,
        problem_checkincheckout,
        problem_comfort_of_bed,
        problem_food_beverage,
        problem_honors_benefits,
        problem_hotel_amenities,
        problem_hvac,
        problem_incidence,
        problem_internet,
        problem_maintenance,
        problem_noise,
        problem_other,
        problem_parking,
        problem_reservation_accuracy,
        problem_room_amenities,
        problem_room_cleanlines,
        problem_room_location,
        problem_safety_security,
        problem_smell,
        problem_staff_interaction,
        problem_working_bathroom,
        property_name,
        quality_fb_restaurant_satisfaction,
        quality_items_evening_experience_rating,
        quality_of_internet_rating,
        received_room_upgrade_rating,
        recommend_rating,
        region,
        resolution_billing_rates,
        resolution_checkincheckout,
        resolution_comfort_of_bed,
        resolution_food_beverage,
        resolution_honors_benefits,
        resolution_hotel_amenities,
        resolution_hvac,
        resolution_internet,
        resolution_maintenance,
        resolution_noise,
        resolution_other,
        resolution_parking,
        resolution_reservation_accuracy,
        resolution_room_amenities,
        resolution_room_cleanliness,
        resolution_room_location,
        resolution_safety_security,
        resolution_smell,
        resolution_staff_interaction,
        resolution_working_bathroom,
        response_date,
        restaurant_lunch_dinner_satisfaction_rating,
        return_to_brand_rating,
        return_to_property_rating,
        room_cleaning_expectation_rating,
        room_number,
        safe_clean_disinfected_environment_rating,
        shuttle_service_experience_rating,
        srp_code,
        staff_anticipated_needs_rating,
        staff_personalized_attention_rating,
        sub_brand,
        survey_alert,
        survey_id,
        survey_language,
        survey_status,
        tiered_internet,
        transfer_lounge_rating,
        used_bar,
        used_bell_service,
        used_breakfast,
        used_concierge,
        used_day_spa,
        used_deli_store,
        used_digital_key,
        used_executive_lounge,
        used_fitness_center,
        used_food_beverage,
        used_grab_go_market,
        used_high_speed_internet,
        used_lobby_games,
        used_lobby_reading_material,
        used_meeting,
        used_none,
        used_pool,
        used_recreation_facilities,
        used_restaurant,
        used_room_service,
        used_work_alcoves,
        value_for_price_rating,
        version,
        weekday_weekend,
        welcome_gift_rating,
        welcomed_club_member,
        welcomed_elite_member,
        work_alcoves_rating,
        working_order_kitchen_appliances_rating,
        source_id,
        etl_file_name,
        etl_ingest_datetime
    )
    SELECT
        case when age is null then null when length(trim(	age)) = 0 is null then null else age end,
        case when alert_overdue is null then null when length(trim(	alert_overdue)) = 0 is null then null else alert_overdue end,
        case when appreciated_elite_tier_honors_rating is null then null when length(trim(	appreciated_elite_tier_honors_rating)) = 0 is null then null else appreciated_elite_tier_honors_rating end,
        case when appreciated_honors_club_member_rating is null then null when length(trim(	appreciated_honors_club_member_rating)) = 0 is null then null else appreciated_honors_club_member_rating end,
        case when appreciated_honors_member_rating is null then null when length(trim(	appreciated_honors_member_rating)) = 0 is null then null else appreciated_honors_member_rating end,
        case when availability_accessibility_food_amenities_rating is null then null when length(trim(	availability_accessibility_food_amenities_rating)) = 0 is null then null else availability_accessibility_food_amenities_rating end,
        case when aware_of_guarantee is null then null when length(trim(	aware_of_guarantee)) = 0 is null then null else aware_of_guarantee end,
        case when bathroom_cleanliness_rating is null then null when length(trim(	bathroom_cleanliness_rating)) = 0 is null then null else bathroom_cleanliness_rating end,
        case when brand is null then null when length(trim(	brand)) = 0 is null then null else brand end,
        case when brand_conversion is null then null when length(trim(	brand_conversion)) = 0 is null then null else brand_conversion end,
        case when brand_promise_rating is null then null when length(trim(	brand_promise_rating)) = 0 is null then null else brand_promise_rating end,
        case when brand_promise_rating_QQ is null then null when length(trim(	brand_promise_rating_QQ)) = 0 is null then null else brand_promise_rating_QQ end,
        case when brand_promise_rating_UP is null then null when length(trim(	brand_promise_rating_UP)) = 0 is null then null else brand_promise_rating_UP end,
        case when breakfast_in_bag_rating is null then null when length(trim(	breakfast_in_bag_rating)) = 0 is null then null else breakfast_in_bag_rating end,
        case when breakfast_item_quality_rating is null then null when length(trim(	breakfast_item_quality_rating)) = 0 is null then null else breakfast_item_quality_rating end,
        case when canopy_breakfast_rating is null then null when length(trim(	canopy_breakfast_rating)) = 0 is null then null else canopy_breakfast_rating end,
        checkin_date,
        case when checkin_type is null then null when length(trim(	checkin_type)) = 0 is null then null else checkin_type end,
        checkout_date,
        case when complimentary_breakfast is null then null when length(trim(	complimentary_breakfast)) = 0 is null then null else complimentary_breakfast end,
        case when condition_of_pool_rating is null then null when length(trim(	condition_of_pool_rating)) = 0 is null then null else condition_of_pool_rating end,
        case when confirmation_number is null then null when length(trim(	confirmation_number)) = 0 is null then null else confirmation_number end,
        case when conrad_concierge_rating is null then null when length(trim(	conrad_concierge_rating)) = 0 is null then null else conrad_concierge_rating end,
        case when digital_checkin_map_usefulness_rating is null then null when length(trim(	digital_checkin_map_usefulness_rating)) = 0 is null then null else digital_checkin_map_usefulness_rating end,
        case when digital_checkin_room_selection_rating is null then null when length(trim(	digital_checkin_room_selection_rating)) = 0 is null then null else digital_checkin_room_selection_rating end,
        case when digital_checkin_satisfaction_rating is null then null when length(trim(	digital_checkin_satisfaction_rating)) = 0 is null then null else digital_checkin_satisfaction_rating end,
        case when digital_key_front_desk_did_not_visit is null then null when length(trim(	digital_key_front_desk_did_not_visit)) = 0 is null then null else digital_key_front_desk_did_not_visit end,
        case when digital_key_front_desk_info is null then null when length(trim(	digital_key_front_desk_info)) = 0 is null then null else digital_key_front_desk_info end,
        case when digital_key_front_desk_obtain_info is null then null when length(trim(	digital_key_front_desk_obtain_info)) = 0 is null then null else digital_key_front_desk_obtain_info end,
        case when digital_key_front_desk_other_reason is null then null when length(trim(	digital_key_front_desk_other_reason)) = 0 is null then null else digital_key_front_desk_other_reason end,
        case when digital_key_front_desk_rating is null then null when length(trim(	digital_key_front_desk_rating)) = 0 is null then null else digital_key_front_desk_rating end,
        case when digital_key_front_desk_report_problem is null then null when length(trim(	digital_key_front_desk_report_problem)) = 0 is null then null else digital_key_front_desk_report_problem end,
        case when digital_key_front_desk_request_amenities is null then null when length(trim(	digital_key_front_desk_request_amenities)) = 0 is null then null else digital_key_front_desk_request_amenities end,
        case when digital_key_rating is null then null when length(trim(	digital_key_rating)) = 0 is null then null else digital_key_rating end,
        case when digital_key_room_selection_rating is null then null when length(trim(	digital_key_room_selection_rating)) = 0 is null then null else digital_key_room_selection_rating end,
        case when digital_key_staff_handling_problem is null then null when length(trim(	digital_key_staff_handling_problem)) = 0 is null then null else digital_key_staff_handling_problem end,
        case when efficiency_of_arrival_rating is null then null when length(trim(	efficiency_of_arrival_rating)) = 0 is null then null else efficiency_of_arrival_rating end,
        case when environmental_programs_rating is null then null when length(trim(	environmental_programs_rating)) = 0 is null then null else environmental_programs_rating end,
        case when evening_manager_reception is null then null when length(trim(	evening_manager_reception)) = 0 is null then null else evening_manager_reception end,
        case when evening_tastings_rating is null then null when length(trim(	evening_tastings_rating)) = 0 is null then null else evening_tastings_rating end,
        facility_id,
        case when front_desk_digital_rating is null then null when length(trim(	front_desk_digital_rating)) = 0 is null then null else front_desk_digital_rating end,
        case when gender is null then null when length(trim(	gender)) = 0 is null then null else gender end,
        case when grab_go_market_rating is null then null when length(trim(	grab_go_market_rating)) = 0 is null then null else grab_go_market_rating end,
        case when guarantee_resolved_experience_rating is null then null when length(trim(	guarantee_resolved_experience_rating)) = 0 is null then null else guarantee_resolved_experience_rating end,
        case when guest_room_cleanliness_rating is null then null when length(trim(	guest_room_cleanliness_rating)) = 0 is null then null else guest_room_cleanliness_rating end,
        case when helpfulness_bell_staff_rating is null then null when length(trim(	helpfulness_bell_staff_rating)) = 0 is null then null else helpfulness_bell_staff_rating end,
        case when helpfulness_breakfast_staff_rating is null then null when length(trim(	helpfulness_breakfast_staff_rating)) = 0 is null then null else helpfulness_breakfast_staff_rating end,
        case when helpfulness_executive_lounge_staff is null then null when length(trim(	helpfulness_executive_lounge_staff)) = 0 is null then null else helpfulness_executive_lounge_staff end,
        case when helpfulness_hotel_staff_rating is null then null when length(trim(	helpfulness_hotel_staff_rating)) = 0 is null then null else helpfulness_hotel_staff_rating end,
        case when helpfulness_staff_evening_experience_rating is null then null when length(trim(	helpfulness_staff_evening_experience_rating)) = 0 is null then null else helpfulness_staff_evening_experience_rating end,
        case when hgv_primary_purpose is null then null when length(trim(	hgv_primary_purpose)) = 0 is null then null else hgv_primary_purpose end,
        case when honors_benefit_delivery_rating is null then null when length(trim(	honors_benefit_delivery_rating)) = 0 is null then null else honors_benefit_delivery_rating end,
        case when honors_benefit_delivery_silver_rating is null then null when length(trim(	honors_benefit_delivery_silver_rating)) = 0 is null then null else honors_benefit_delivery_silver_rating end,
        case when honors_member_welcome_rating is null then null when length(trim(	honors_member_welcome_rating)) = 0 is null then null else honors_member_welcome_rating end,
        case when honors_tier is null then null when length(trim(	honors_tier)) = 0 is null then null else honors_tier end,
        case when hotel_ground_apprearance_rating is null then null when length(trim(	hotel_ground_apprearance_rating)) = 0 is null then null else hotel_ground_apprearance_rating end,
        case when housekeeping_acknowledge_rating is null then null when length(trim(	housekeeping_acknowledge_rating)) = 0 is null then null else housekeeping_acknowledge_rating end,
        case when inncode is null then null when length(trim(	inncode)) = 0 is null then null else inncode end,
        insert_datetime_utc,
        case when lobby_apprearance_rating is null then null when length(trim(	lobby_apprearance_rating)) = 0 is null then null else lobby_apprearance_rating end,
        case when lobby_games_rating is null then null when length(trim(	lobby_games_rating)) = 0 is null then null else lobby_games_rating end,
        case when lobby_reading_material_rating is null then null when length(trim(	lobby_reading_material_rating)) = 0 is null then null else lobby_reading_material_rating end,
        case when luxurious_stay_rating is null then null when length(trim(	luxurious_stay_rating)) = 0 is null then null else luxurious_stay_rating end,
        case when make_it_right_rating is null then null when length(trim(	make_it_right_rating)) = 0 is null then null else make_it_right_rating end,
        case when mobile_opt_in is null then null when length(trim(	mobile_opt_in)) = 0 is null then null else mobile_opt_in end,
        case when offered_cookie_ind is null then null when length(trim(	offered_cookie_ind)) = 0 is null then null else offered_cookie_ind end,
        case when overall_accommodation_rating is null then null when length(trim(	overall_accommodation_rating)) = 0 is null then null else overall_accommodation_rating end,
        case when overall_arrival_rating is null then null when length(trim(	overall_arrival_rating)) = 0 is null then null else overall_arrival_rating end,
        case when overall_bar_experience_rating is null then null when length(trim(	overall_bar_experience_rating)) = 0 is null then null else overall_bar_experience_rating end,
        case when overall_breakfast_experience_rating is null then null when length(trim(	overall_breakfast_experience_rating)) = 0 is null then null else overall_breakfast_experience_rating end,
        case when overall_concierge_experience_rating is null then null when length(trim(	overall_concierge_experience_rating)) = 0 is null then null else overall_concierge_experience_rating end,
        case when overall_departure_rating is null then null when length(trim(	overall_departure_rating)) = 0 is null then null else overall_departure_rating end,
        case when overall_event_experience_rating is null then null when length(trim(	overall_event_experience_rating)) = 0 is null then null else overall_event_experience_rating end,
        case when overall_exec_lounge_experience_rating is null then null when length(trim(	overall_exec_lounge_experience_rating)) = 0 is null then null else overall_exec_lounge_experience_rating end,
        case when overall_experience_rating is null then null when length(trim(	overall_experience_rating)) = 0 is null then null else overall_experience_rating end,
        case when overall_fitness_facility_rating is null then null when length(trim(	overall_fitness_facility_rating)) = 0 is null then null else overall_fitness_facility_rating end,
        case when overall_food_beverage_experience_rating is null then null when length(trim(	overall_food_beverage_experience_rating)) = 0 is null then null else overall_food_beverage_experience_rating end,
        case when overall_inroom_service_experience is null then null when length(trim(	overall_inroom_service_experience)) = 0 is null then null else overall_inroom_service_experience end,
        case when overall_reception_experience_rating is null then null when length(trim(	overall_reception_experience_rating)) = 0 is null then null else overall_reception_experience_rating end,
        case when overall_service_rating is null then null when length(trim(	overall_service_rating)) = 0 is null then null else overall_service_rating end,
        case when overall_spa_experience_rating is null then null when length(trim(	overall_spa_experience_rating)) = 0 is null then null else overall_spa_experience_rating end,
        case when owner_account_id is null then null when length(trim(	owner_account_id)) = 0 is null then null else owner_account_id end,
        case when owner_account_name is null then null when length(trim(	owner_account_name)) = 0 is null then null else owner_account_name end,
        case when owner_extract_type is null then null when length(trim(	owner_extract_type)) = 0 is null then null else owner_extract_type end,
        case when partial_survey_flag is null then null when length(trim(	partial_survey_flag)) = 0 is null then null else partial_survey_flag end,
        partition_date,
        case when pay_access_premium_suite_rating is null then null when length(trim(	pay_access_premium_suite_rating)) = 0 is null then null else pay_access_premium_suite_rating end,
        case when premium_suite_during_stay_rating is null then null when length(trim(	premium_suite_during_stay_rating)) = 0 is null then null else premium_suite_during_stay_rating end,
        case when premium_suite_value_rating is null then null when length(trim(	premium_suite_value_rating)) = 0 is null then null else premium_suite_value_rating end,
        case when primary_purpose is null then null when length(trim(	primary_purpose)) = 0 is null then null else primary_purpose end,
        case when problem_billing_rates is null then null when length(trim(	problem_billing_rates)) = 0 is null then null else problem_billing_rates end,
        case when problem_checkincheckout is null then null when length(trim(	problem_checkincheckout)) = 0 is null then null else problem_checkincheckout end,
        case when problem_comfort_of_bed is null then null when length(trim(	problem_comfort_of_bed)) = 0 is null then null else problem_comfort_of_bed end,
        case when problem_food_beverage is null then null when length(trim(	problem_food_beverage)) = 0 is null then null else problem_food_beverage end,
        case when problem_honors_benefits is null then null when length(trim(	problem_honors_benefits)) = 0 is null then null else problem_honors_benefits end,
        case when problem_hotel_amenities is null then null when length(trim(	problem_hotel_amenities)) = 0 is null then null else problem_hotel_amenities end,
        case when problem_hvac is null then null when length(trim(	problem_hvac)) = 0 is null then null else problem_hvac end,
        case when problem_incidence is null then null when length(trim(	problem_incidence)) = 0 is null then null else problem_incidence end,
        case when problem_internet is null then null when length(trim(	problem_internet)) = 0 is null then null else problem_internet end,
        case when problem_maintenance is null then null when length(trim(	problem_maintenance)) = 0 is null then null else problem_maintenance end,
        case when problem_noise is null then null when length(trim(	problem_noise)) = 0 is null then null else problem_noise end,
        case when problem_other is null then null when length(trim(	problem_other)) = 0 is null then null else problem_other end,
        case when problem_parking is null then null when length(trim(	problem_parking)) = 0 is null then null else problem_parking end,
        case when problem_reservation_accuracy is null then null when length(trim(	problem_reservation_accuracy)) = 0 is null then null else problem_reservation_accuracy end,
        case when problem_room_amenities is null then null when length(trim(	problem_room_amenities)) = 0 is null then null else problem_room_amenities end,
        case when problem_room_cleanlines is null then null when length(trim(	problem_room_cleanlines)) = 0 is null then null else problem_room_cleanlines end,
        case when problem_room_location is null then null when length(trim(	problem_room_location)) = 0 is null then null else problem_room_location end,
        case when problem_safety_security is null then null when length(trim(	problem_safety_security)) = 0 is null then null else problem_safety_security end,
        case when problem_smell is null then null when length(trim(	problem_smell)) = 0 is null then null else problem_smell end,
        case when problem_staff_interaction is null then null when length(trim(	problem_staff_interaction)) = 0 is null then null else problem_staff_interaction end,
        case when problem_working_bathroom is null then null when length(trim(	problem_working_bathroom)) = 0 is null then null else problem_working_bathroom end,
        case when property_name is null then null when length(trim(	property_name)) = 0 is null then null else property_name end,
        case when quality_fb_restaurant_satisfaction is null then null when length(trim(	quality_fb_restaurant_satisfaction)) = 0 is null then null else quality_fb_restaurant_satisfaction end,
        case when quality_items_evening_experience_rating is null then null when length(trim(	quality_items_evening_experience_rating)) = 0 is null then null else quality_items_evening_experience_rating end,
        case when quality_of_internet_rating is null then null when length(trim(	quality_of_internet_rating)) = 0 is null then null else quality_of_internet_rating end,
        case when received_room_upgrade_rating is null then null when length(trim(	received_room_upgrade_rating)) = 0 is null then null else received_room_upgrade_rating end,
        case when recommend_rating is null then null when length(trim(	recommend_rating)) = 0 is null then null else recommend_rating end,
        case when region is null then null when length(trim(	region)) = 0 is null then null else region end,
        case when resolution_billing_rates is null then null when length(trim(	resolution_billing_rates)) = 0 is null then null else resolution_billing_rates end,
        case when resolution_checkincheckout is null then null when length(trim(	resolution_checkincheckout)) = 0 is null then null else resolution_checkincheckout end,
        case when resolution_comfort_of_bed is null then null when length(trim(	resolution_comfort_of_bed)) = 0 is null then null else resolution_comfort_of_bed end,
        case when resolution_food_beverage is null then null when length(trim(	resolution_food_beverage)) = 0 is null then null else resolution_food_beverage end,
        case when resolution_honors_benefits is null then null when length(trim(	resolution_honors_benefits)) = 0 is null then null else resolution_honors_benefits end,
        case when resolution_hotel_amenities is null then null when length(trim(	resolution_hotel_amenities)) = 0 is null then null else resolution_hotel_amenities end,
        case when resolution_hvac is null then null when length(trim(	resolution_hvac)) = 0 is null then null else resolution_hvac end,
        case when resolution_internet is null then null when length(trim(	resolution_internet)) = 0 is null then null else resolution_internet end,
        case when resolution_maintenance is null then null when length(trim(	resolution_maintenance)) = 0 is null then null else resolution_maintenance end,
        case when resolution_noise is null then null when length(trim(	resolution_noise)) = 0 is null then null else resolution_noise end,
        case when resolution_other is null then null when length(trim(	resolution_other)) = 0 is null then null else resolution_other end,
        case when resolution_parking is null then null when length(trim(	resolution_parking)) = 0 is null then null else resolution_parking end,
        case when resolution_reservation_accuracy is null then null when length(trim(	resolution_reservation_accuracy)) = 0 is null then null else resolution_reservation_accuracy end,
        case when resolution_room_amenities is null then null when length(trim(	resolution_room_amenities)) = 0 is null then null else resolution_room_amenities end,
        case when resolution_room_cleanliness is null then null when length(trim(	resolution_room_cleanliness)) = 0 is null then null else resolution_room_cleanliness end,
        case when resolution_room_location is null then null when length(trim(	resolution_room_location)) = 0 is null then null else resolution_room_location end,
        case when resolution_safety_security is null then null when length(trim(	resolution_safety_security)) = 0 is null then null else resolution_safety_security end,
        case when resolution_smell is null then null when length(trim(	resolution_smell)) = 0 is null then null else resolution_smell end,
        case when resolution_staff_interaction is null then null when length(trim(	resolution_staff_interaction)) = 0 is null then null else resolution_staff_interaction end,
        case when resolution_working_bathroom is null then null when length(trim(	resolution_working_bathroom)) = 0 is null then null else resolution_working_bathroom end,
        response_date,
        case when restaurant_lunch_dinner_satisfaction_rating is null then null when length(trim(	restaurant_lunch_dinner_satisfaction_rating)) = 0 is null then null else restaurant_lunch_dinner_satisfaction_rating end,
        case when return_to_brand_rating is null then null when length(trim(	return_to_brand_rating)) = 0 is null then null else return_to_brand_rating end,
        case when return_to_property_rating is null then null when length(trim(	return_to_property_rating)) = 0 is null then null else return_to_property_rating end,
        case when room_cleaning_expectation_rating is null then null when length(trim(	room_cleaning_expectation_rating)) = 0 is null then null else room_cleaning_expectation_rating end,
        case when room_number is null then null when length(trim(	room_number)) = 0 is null then null else room_number end,
        case when safe_clean_disinfected_environment_rating is null then null when length(trim(	safe_clean_disinfected_environment_rating)) = 0 is null then null else safe_clean_disinfected_environment_rating end,
        case when shuttle_service_experience_rating is null then null when length(trim(	shuttle_service_experience_rating)) = 0 is null then null else shuttle_service_experience_rating end,
        case when srp_code is null then null when length(trim(	srp_code)) = 0 is null then null else srp_code end,
        case when staff_anticipated_needs_rating is null then null when length(trim(	staff_anticipated_needs_rating)) = 0 is null then null else staff_anticipated_needs_rating end,
        case when staff_personalized_attention_rating is null then null when length(trim(	staff_personalized_attention_rating)) = 0 is null then null else staff_personalized_attention_rating end,
        case when sub_brand is null then null when length(trim(	sub_brand)) = 0 is null then null else sub_brand end,
        survey_alert,
        survey_id,
        case when survey_language is null then null when length(trim(	survey_language)) = 0 is null then null else survey_language end,
        case when survey_status is null then null when length(trim(	survey_status)) = 0 is null then null else survey_status end,
        case when tiered_internet is null then null when length(trim(	tiered_internet)) = 0 is null then null else tiered_internet end,
        case when transfer_lounge_rating is null then null when length(trim(	transfer_lounge_rating)) = 0 is null then null else transfer_lounge_rating end,
        case when used_bar is null then null when length(trim(	used_bar)) = 0 is null then null else used_bar end,
        case when used_bell_service is null then null when length(trim(	used_bell_service)) = 0 is null then null else used_bell_service end,
        case when used_breakfast is null then null when length(trim(	used_breakfast)) = 0 is null then null else used_breakfast end,
        case when used_concierge is null then null when length(trim(	used_concierge)) = 0 is null then null else used_concierge end,
        case when used_day_spa is null then null when length(trim(	used_day_spa)) = 0 is null then null else used_day_spa end,
        case when used_deli_store is null then null when length(trim(	used_deli_store)) = 0 is null then null else used_deli_store end,
        case when used_digital_key is null then null when length(trim(	used_digital_key)) = 0 is null then null else used_digital_key end,
        case when used_executive_lounge is null then null when length(trim(	used_executive_lounge)) = 0 is null then null else used_executive_lounge end,
        case when used_fitness_center is null then null when length(trim(	used_fitness_center)) = 0 is null then null else used_fitness_center end,
        case when used_food_beverage is null then null when length(trim(	used_food_beverage)) = 0 is null then null else used_food_beverage end,
        case when used_grab_go_market is null then null when length(trim(	used_grab_go_market)) = 0 is null then null else used_grab_go_market end,
        case when used_high_speed_internet is null then null when length(trim(	used_high_speed_internet)) = 0 is null then null else used_high_speed_internet end,
        case when used_lobby_games is null then null when length(trim(	used_lobby_games)) = 0 is null then null else used_lobby_games end,
        case when used_lobby_reading_material is null then null when length(trim(	used_lobby_reading_material)) = 0 is null then null else used_lobby_reading_material end,
        case when used_meeting is null then null when length(trim(	used_meeting)) = 0 is null then null else used_meeting end,
        case when used_none is null then null when length(trim(	used_none)) = 0 is null then null else used_none end,
        case when used_pool is null then null when length(trim(	used_pool)) = 0 is null then null else used_pool end,
        case when used_recreation_facilities is null then null when length(trim(	used_recreation_facilities)) = 0 is null then null else used_recreation_facilities end,
        case when used_restaurant is null then null when length(trim(	used_restaurant)) = 0 is null then null else used_restaurant end,
        case when used_room_service is null then null when length(trim(	used_room_service)) = 0 is null then null else used_room_service end,
        case when used_work_alcoves is null then null when length(trim(	used_work_alcoves)) = 0 is null then null else used_work_alcoves end,
        case when value_for_price_rating is null then null when length(trim(	value_for_price_rating)) = 0 is null then null else value_for_price_rating end,
        case when version is null then null when length(trim(	version)) = 0 is null then null else version end,
        case when weekday_weekend is null then null when length(trim(	weekday_weekend)) = 0 is null then null else weekday_weekend end,
        case when welcome_gift_rating is null then null when length(trim(	welcome_gift_rating)) = 0 is null then null else welcome_gift_rating end,
        case when welcomed_club_member is null then null when length(trim(	welcomed_club_member)) = 0 is null then null else welcomed_club_member end,
        case when welcomed_elite_member is null then null when length(trim(	welcomed_elite_member)) = 0 is null then null else welcomed_elite_member end,
        case when work_alcoves_rating is null then null when length(trim(	work_alcoves_rating)) = 0 is null then null else work_alcoves_rating end,
        case when working_order_kitchen_appliances_rating is null then null when length(trim(	working_order_kitchen_appliances_rating)) = 0 is null then null else working_order_kitchen_appliances_rating end,
        sourceId,
        etl_file_name,
        current_timestamp
    FROM
        t_stage_to_warehouse_onq_salt;
    -- Update status in stage.stage_batch
    UPDATE
        stage.stage_batch b
    SET
        warehouse_completed_ind = true,
        warehouse_transfer_completed_timestamp = current_timestamp
    FROM
            t_stage_to_warehouse_onq_salt o
        WHERE
            o.etl_batch_id = b.batch_id;
    -- END - insert into warehouse tables.
    -- START CLEAN UP

    DELETE FROM
        stage.stage_onq_salt s
    USING
       t_stage_to_warehouse_onq_salt t
    WHERE
        s.etl_batch_id = t.etl_batch_id;
  	DROP TABLE IF EXISTS t_stage_to_warehouse_onq_salt;
    return null;
END
$BODY$;


select lookup.f_process_warehouse_onq_salt(null);
